theme: jekyll-theme-cayman
title: [Julia Plots Gallery]
description: [These figures are made by Plots.jl]
show_downloads: ["false"]
google_analytics: UA-112840751-1
url: https://goropikari.github.io/PlotsGallery.jl
